version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./api:/api
      - ./static:/static
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'