version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - ./api:/api
      - ./static:/static
      - ./mysql:/mysql
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
    depends_on:
     - db    

  db:
    image: mysql:5.7    # 3
    environment:                  # 4
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
